---
baseurl: "http://ryanmartinsen.com"

FootnoteReturnLinkContents: "↩"

params:
  shortlink: http://ryanm.me/XqVE5S
  meta_description: Ryan Martinsen is an Orlando based web developer specializing in PHP, Python, JavaScript, MySQL, and MongoDB.

permalinks:
  article: "/article/:filename/"
  page: "/:filename/"
---
